// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import DiagnosisController from "./diagnosis_controller"
application.register("diagnosis", DiagnosisController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import MenuToggleController from "./menu_toggle_controller"
application.register("menu-toggle", MenuToggleController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)
